apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: nutanix-ccm
  behavior: merge
  files:
  - nutanix-ccm.yaml

namespace: "${NAMESPACE}"

bases:
  - ../base-root
  - ./nutanix-cluster.yaml
  - ./cluster-without-topology.yaml
  - ./kcp.yaml
  - ./nmt.yaml
  - ./md.yaml
  - ./mhc.yaml
  - ./nutanix-ccm-crs.yaml
  - ./nutanix-ccm-secret.yaml

patchesStrategicMerge:
- ccm-patch.yaml

