apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: "${CLUSTER_CLASS_NAME}"
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: ${CLUSTER_CLASS_NAME}-kcpt
      namespace: ${NAMESPACE}
    machineInfrastructure:
      ref:
        kind: NutanixMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: ${CLUSTER_CLASS_NAME}-cp-nmt
        namespace: ${NAMESPACE}
    machineHealthCheck:
      maxUnhealthy: 40%
      nodeStartupTimeout: 10m
      unhealthyConditions:
        - type: Ready
          status: "False"
          timeout: 300s
        - type: Ready
          status: Unknown
          timeout: 300s
        - type: MemoryPressure
          status: "True"
          timeout: 300s
        - type: DiskPressure
          status: "True"
          timeout: 300s
        - type: PIDPressure
          status: "True"
          timeout: 300s
        - type: NetworkUnavailable
          status: "True"
          timeout: 300s
  workers:
    machineDeployments:
    - class: ${CLUSTER_CLASS_NAME}-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: "${CLUSTER_NAME}-kcfg-0"
            namespace: ${NAMESPACE}
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: NutanixMachineTemplate
            name: ${CLUSTER_CLASS_NAME}-md-nmt
            namespace: ${NAMESPACE}
      machineHealthCheck:
        maxUnhealthy: 40%
        nodeStartupTimeout: 10m
        unhealthyConditions:
          - type: Ready
            status: "False"
            timeout: 300s
          - type: Ready
            status: Unknown
            timeout: 300s
          - type: MemoryPressure
            status: "True"
            timeout: 300s
          - type: DiskPressure
            status: "True"
            timeout: 300s
          - type: PIDPressure
            status: "True"
            timeout: 300s
          - type: NetworkUnavailable
            status: "True"
            timeout: 300s
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: NutanixClusterTemplate
      name: ${CLUSTER_CLASS_NAME}-nct
      namespace: ${NAMESPACE}
  patches:
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/users
        valueFrom:
          template: |
            - name: capxuser
              lockPassword: false
              sudo: ALL=(ALL) NOPASSWD:ALL
              sshAuthorizedKeys:
                - '{{ .sshKey }}'
      selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
    - jsonPatches:
      - op: add
        path: /spec/template/spec/users
        valueFrom:
          template: |
            - name: capxuser
              lockPassword: false
              sudo: ALL=(ALL) NOPASSWD:ALL
              sshAuthorizedKeys:
                - '{{ .sshKey }}'
      selector:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
        kind: KubeadmConfigTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - ${CLUSTER_CLASS_NAME}-worker
    name: add-ssh-user
  - definitions:
    - jsonPatches:
          - op: add
            path: /spec/template/spec/controlPlaneEndpoint
            valueFrom:
              template: |
                host: '{{ .controlPlaneEndpoint.IP }}'
                port: {{ .controlPlaneEndpoint.port }}
      selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: NutanixClusterTemplate
        matchResources:
          infrastructureCluster: true
    name: add-control-plane-endpoint
  - definitions:
    - jsonPatches:
          - op: add
            path: /spec/template/spec/prismCentral
            valueFrom:
              template: |
                address: '{{ .prismCentralEndpoint.address }}'
                port: {{ .prismCentralEndpoint.port }}
                insecure: {{ .prismCentralEndpoint.insecure }}
                credentialRef:
                  name: "${CLUSTER_NAME}"
                  kind: Secret
                additionalTrustBundle:
                  name: ${CLUSTER_NAME}-pc-trusted-ca-bundle
                  kind: ConfigMap
      selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: NutanixClusterTemplate
        matchResources:
          infrastructureCluster: true
    name: add-pc-endpoint-and-creds
  variables:
  - name: sshKey
    required: true
    schema:
      openAPIV3Schema:
        description: Public key to SSH onto the cluster nodes.
        type: string
  - name: controlPlaneEndpoint
    required: true
    schema:
      openAPIV3Schema:
        properties:
          IP:
            type: string
          port:
            type: integer
        type: object
  - name: prismCentralEndpoint
    required: true
    schema:
      openAPIV3Schema:
        properties:
          address:
            type: string
          port:
            type: integer
          insecure:
            type: boolean
        type: object