apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixCluster
metadata:
  name: "${CLUSTER_NAME}"
  namespace: "${NAMESPACE}"
spec:
  prismCentral:
    address: "${NUTANIX_ENDPOINT}"
    port: ${NUTANIX_PORT=9440}
    insecure: ${NUTANIX_INSECURE=false}
    credentialRef:
      name: "${CLUSTER_NAME}"
      kind: Secret
  controlPlaneEndpoint:
    host: "${CONTROL_PLANE_ENDPOINT_IP}"
    port: ${CONTROL_PLANE_ENDPOINT_PORT=6443}
---
apiVersion: v1
kind: Secret
metadata:
  name: "${CLUSTER_NAME}"
  namespace: "${NAMESPACE}"
stringData:
  NUTANIX_PASSWORD: "${NUTANIX_PASSWORD}"
  NUTANIX_USER: "${NUTANIX_USER}"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["172.19.0.0/16"]
    pods:
      cidrBlocks: ["172.20.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: "${CLUSTER_CLASS_NAME}"
    version: ${KUBERNETES_VERSION}
    controlPlane:
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
      metadata: {}
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: ${WORKER_MACHINE_COUNT}
        metadata: {}
---