apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixClusterTemplate
metadata:
  name: ${CLUSTER_CLASS_NAME}-nct
spec:
  template: 
    spec:
      failureDomains: []
      prismCentral:
        address: "${NUTANIX_ENDPOINT}"
        port: ${NUTANIX_PORT=9440}
        insecure: ${NUTANIX_INSECURE=false}
        credentialRef:
          name: "${CLUSTER_NAME}"
          kind: Secret
        additionalTrustBundle:
          name: ${CLUSTER_NAME}-pc-trusted-ca-bundle
          kind: ConfigMap