name: Black Duck Policy Check
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  security:
    if: github.repository == 'nutanix-cloud-native/cluster-api-provider-nutanix'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.19"

      - name: Build Project
        run: make build

      - name: Run Synopsys Detect
        uses: synopsys-sig/synopsys-action@v1.6.0
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_scan_failure_severities: 'ALL'
          blackduck_prComment_enabled: false
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          # blackduck_scan_full: true